baseURL = "https://juliakorovsky.github.io/korovsky-static-site/"
languageCode = "ru"
title = "korovsky"
theme = "PaperMod"

[params]
  showReadingTime = false
  showShareButtons = false
  defaultTheme = "auto"

  [[menu.main]]
  name = "Обо мне"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Посты"
  url = "/posts/"
  weight = 2
